(ns epiphany.law.assurance
  "Contract for the CI assurance evidence artifact (ENG-017J, ADR-004
   decision 7). The artifact is generated by execution and validated
   against this schema before being written — the assurance pipeline
   dogfoods its own contract machinery.")

(def artifact-schema
  "Schema for one revision-bound assurance evidence artifact."
  [:map {:closed true}
   [:artifact/version [:= 1]]
   [:revision [:map {:closed true}
               [:sha :string]
               [:branch :string]
               [:dirty? :boolean]]]
   [:generated-at :string]
   [:commands [:vector [:map {:closed true}
                        [:name :string]
                        [:exit :int]
                        [:summary :string]]]]
   [:property-seeds [:vector [:map {:closed true}
                              [:label :string]
                              [:seed :int]]]]
   [:interop [:map {:closed true}
              [:baseline-clean? :boolean]
              [:delta :string]]]
   [:suites [:map {:closed true}
             [:unit [:map {:closed true}
                     [:tests :int]
                     [:assertions :int]
                     [:failures :int]
                     [:errors :int]]]]]])

(def schemas
  {"assurance/evidence-artifact-v1" artifact-schema})
