(ns epiphany.assurance-evidence
  "ENG-017J: CI assurance evidence artifact generator.

   Runs the assurance commands, captures their outputs verbatim, and
   emits ONE revision-bound EDN artifact per checked revision:

     {:artifact/version 1
      :revision {:sha ... :branch ... :dirty? ...}
      :generated-at ...
      :commands [{:name ... :argv [...] :exit ... :summary ...}]
      :property-seeds [...]
      :interop {:baseline-clean? ... :delta {...}}
      :suites {:unit {...} :integration {...}}}

   The artifact is GENERATED BY EXECUTION — never authored or edited by
   an agent or human. It validates against the Malli schema in
   `artifact-schema` before being written (dogfood: the assurance
   pipeline is itself contract-checked)."
  (:require [clojure.java.shell :as shell]
            [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [epiphany.law.assurance]
            [malli.core :as m]))

;; ---------------------------------------------------------------------------
;; Artifact schema — lives in law/assurance (ENG-017J review finding: the
;; contract belongs in law/, not in the generator).

(def artifact-schema
  epiphany.law.assurance/artifact-schema)

;; ---------------------------------------------------------------------------
;; Execution capture

(defn- run-command
  "Run a command, capturing exit + the last meaningful output line as
   the summary. Never throws: a failed command is evidence, not a fault."
  [name argv]
  (let [{:keys [exit out err]} (apply shell/sh argv)
        lines (remove str/blank? (str/split-lines (str out err)))
        summary (or (last lines) "")]
    {:name name
     :exit exit
     :summary (str/trim summary)}))

(defn- git
  [& args]
  (let [{:keys [exit out]} (apply shell/sh "git" args)]
    (when (zero? exit)
      (str/trim out))))

(defn- revision-info
  []
  {:sha (or (git "rev-parse" "HEAD") "unknown")
   :branch (or (git "rev-parse" "--abbrev-ref" "HEAD") "unknown")
   :dirty? (boolean (seq (git "status" "--porcelain")))})

(defn- strip-ansi
  [s]
  (str/replace s #"\u001b\[[0-9;]*m" ""))

(defn parse-suite-summary
  "Parse a kaocha 'N tests, N assertions, N failures[, N errors]' line."
  [summary]
  (let [[_ tests assertions failures errors]
        (re-find #"(\d+) tests?, (\d+) assertions?, (\d+) failures?(?:, (\d+) errors?)?"
                 (strip-ansi summary))]
    {:tests (Integer/parseInt (or tests "0"))
     :assertions (Integer/parseInt (or assertions "0"))
     :failures (Integer/parseInt (or failures "0"))
     :errors (Integer/parseInt (or errors "0"))}))

(defn- property-seeds
  "Seeds recorded by the property runner in target/property-seeds.edn
   (kaocha's capture-output swallows console prints; the file is the
   durable record)."
  []
  (let [seed-file (io/file "target/property-seeds.edn")]
    (if (.exists seed-file)
      (into []
            (keep (fn [line]
                    (when-not (str/blank? line)
                      (edn/read-string line))))
            (line-seq (io/reader seed-file)))
      [])))

(defn- interop-delta
  "Compare the committed interop baseline against a fresh scan."
  []
  (let [baseline-file (io/file "reports/interop.edn")]
    (if-not (.exists baseline-file)
      {:baseline-clean? false :delta "reports/interop.edn missing"}
      (try
        (require 'epiphany.static.interop-inventory)
        (let [scan (resolve 'epiphany.static.interop-inventory/scan-source-tree)
              ratchet (resolve 'epiphany.static.interop-inventory/ratchet-violations)
              baseline-raw (edn/read-string (slurp baseline-file))
              baseline (into {} (map (fn [[k v]] [k (assoc v :ns k)])) baseline-raw)
              current (scan "src")
              violations (ratchet baseline current #{})]
          {:baseline-clean? (empty? violations)
           :delta (pr-str violations)})
        (catch Exception e
          {:baseline-clean? false :delta (str "scan failed: " (.getMessage e))})))))

;; ---------------------------------------------------------------------------
;; Artifact generation

(defn generate-artifact
  "Run the assurance commands and build the artifact map."
  []
  (let [unit (let [{:keys [exit out err]} (shell/sh "clojure" "-M:unit-test")
                   output (strip-ansi (str out err))
                   summary (or (some #(when (re-find #"\d+ tests?, \d+ assertions?" %) %)
                                     (str/split-lines output))
                               "")]
               {:exit exit
                :summary summary})
        boundary (run-command "boundary-check" ["clojure" "-M:boundary-check"])
        interop (interop-delta)
        revision (revision-info)
        artifact {:artifact/version 1
                  :revision revision
                  :generated-at (str (java.time.Instant/now))
                  :commands [{:name "unit-test"
                              :exit (:exit unit)
                              :summary (:summary unit)}
                             boundary]
                  :property-seeds (property-seeds)
                  :interop interop
                  :suites {:unit (parse-suite-summary (:summary unit))}}]
    (when-not (m/validate artifact-schema artifact)
      (throw (ex-info "Generated assurance artifact fails its own schema (dogfood)"
                      {:explanation (m/explain artifact-schema artifact)})))
    artifact))

(defn write-artifact!
  [artifact dir]
  (let [file (io/file dir (str "assurance-" (get-in artifact [:revision :sha]) ".edn"))]
    (io/make-parents file)
    (spit file (pr-str artifact))
    (str file)))

(defn -main
  [& args]
  (let [dir (or (first args) "target/assurance")
        artifact (generate-artifact)
        file (write-artifact! artifact dir)]
    (println (str "Wrote " file))
    (println (str "Unit: " (get-in artifact [:suites :unit])))
    (println (str "Interop baseline clean: " (get-in artifact [:interop :baseline-clean?])))))
